name: project_travel_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Century Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
          weight: 400

        - asset: assets/fonts/gothicb.ttf
          weight: 700
      
  assets:
    - assets/images/
    - assets/images/italy/
    - assets/images/france/
    - assets/images/germany/
    - assets/images/turkey/
    - assets/images/egypt/
    - assets/images/uae/